imports:
    - { resource: 'tables.yml' }

services:
    dmzx.counter.admin.controller:
        class: 'dmzx\counter\controller\admin_controller'
        arguments:
            - '@config'
            - '@template'
            - '@log'
            - '@user'
            - '@request'
    dmzx.counter.cron.task.core.counter:
        class: 'dmzx\counter\cron\prune_counter'
        arguments:
            - '@config'
            - '@dbal.conn'
            - '%dmzx.counter.table.counter%'
        calls:
            - ['set_name', ['cron.task.core.counter']]
        tags:
            - { name: 'cron.task' }
    dmzx.counter.listener:
        class: 'dmzx\counter\event\listener'
        arguments:
            - '@config'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '%dmzx.counter.table.counter%'
        tags:
            - { name: 'event.listener' }
